<?xml version="1.0" encoding="utf-8"?><Database Name="Cua_Hang_Tra_Sua" Class="Cua_Hang_Tra_SuaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-PCHKGH1\SQLEXPRESS;Initial Catalog=Cua_Hang_Tra_Sua;Integrated Security=True;Encrypt=True;Trust Server Certificate=True" SettingsObjectName="Cua_Hang_Tra_Sua.Properties.Settings" SettingsPropertyName="Cua_Hang_Tra_SuaConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Bai_Viet" Member="Bai_Viets">
    <Type Name="Bai_Viet">
      <Column Name="ID_BV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_MN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tieu_de" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Tom_tac" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Noi_dung" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Hinh_anh_page" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="OrderKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Menus_Bai_Viet" Member="Menus" ThisKey="ID_MN" OtherKey="ID_MN" Type="Menus" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tai_Khoan" Member="Tai_Khoans">
    <Type Name="Tai_Khoan">
      <Column Name="Ho_va_ten" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="So_dien_thoai" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Dia_chi" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Mat_khau" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Phan_quyen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Tai_Khoan_Chi_Tiet_Don_Hang" Member="Chi_Tiet_Don_Hangs" ThisKey="So_dien_thoai" OtherKey="So_dien_thoai" Type="Chi_Tiet_Don_Hang" />
      <Association Name="Tai_Khoan_Lich_Su_Don_Hang" Member="Lich_Su_Don_Hangs" ThisKey="So_dien_thoai" OtherKey="So_dien_thoai" Type="Lich_Su_Don_Hang" />
    </Type>
  </Table>
  <Table Name="dbo.Chi_Tiet_Don_Hang" Member="Chi_Tiet_Don_Hangs">
    <Type Name="Chi_Tiet_Don_Hang">
      <Column Name="ID_CTDH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="So_dien_thoai" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Hinh_thuc_dat_don" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Trang_thai_don" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tong_tien" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Ghi_chu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Chi_Tiet_Don_Hang_SP_Don_Hang" Member="SP_Don_Hangs" ThisKey="ID_CTDH" OtherKey="ID_CTDH" Type="SP_Don_Hang" />
      <Association Name="Tai_Khoan_Chi_Tiet_Don_Hang" Member="Tai_Khoan" ThisKey="So_dien_thoai" OtherKey="So_dien_thoai" Type="Tai_Khoan" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Lich_Su_Don_Hang" Member="Lich_Su_Don_Hangs">
    <Type Name="Lich_Su_Don_Hang">
      <Column Name="ID_LSDH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_DH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="So_dien_thoai" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Ngay_gio_ghi_nhan" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Trang_thai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ghi_chu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Tai_Khoan_Lich_Su_Don_Hang" Member="Tai_Khoan" ThisKey="So_dien_thoai" OtherKey="So_dien_thoai" Type="Tai_Khoan" IsForeignKey="true" />
      <Association Name="SP_Don_Hang_Lich_Su_Don_Hang" Member="SP_Don_Hang" ThisKey="ID_DH" OtherKey="ID_DH" Type="SP_Don_Hang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Menus" Member="Menus">
    <Type Name="Menus">
      <Column Name="ID_MN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Parent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Label" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="UrlLink" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="OrderKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Menus_Bai_Viet" Member="Bai_Viets" ThisKey="ID_MN" OtherKey="ID_MN" Type="Bai_Viet" />
      <Association Name="Menus_San_Pham" Member="San_Phams" ThisKey="ID_MN" OtherKey="ID_MN" Type="San_Pham" />
    </Type>
  </Table>
  <Table Name="dbo.San_Pham" Member="San_Phams">
    <Type Name="San_Pham">
      <Column Name="ID_SP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_MN" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ten_san_pham" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Gia_co_ban" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Mo_ta_san_pham" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Hinh_anh" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Trang_thai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="San_Pham_SP_Don_Hang" Member="SP_Don_Hangs" ThisKey="ID_SP" OtherKey="ID_SP" Type="SP_Don_Hang" />
      <Association Name="Menus_San_Pham" Member="Menus" ThisKey="ID_MN" OtherKey="ID_MN" Type="Menus" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SP_Don_Hang" Member="SP_Don_Hangs">
    <Type Name="SP_Don_Hang">
      <Column Name="ID_DH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_CTDH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ID_SP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="So_luong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Gia_Ban" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Ghi_chu_item" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="SP_Don_Hang_Lich_Su_Don_Hang" Member="Lich_Su_Don_Hangs" ThisKey="ID_DH" OtherKey="ID_DH" Type="Lich_Su_Don_Hang" />
      <Association Name="Chi_Tiet_Don_Hang_SP_Don_Hang" Member="Chi_Tiet_Don_Hang" ThisKey="ID_CTDH" OtherKey="ID_CTDH" Type="Chi_Tiet_Don_Hang" IsForeignKey="true" />
      <Association Name="San_Pham_SP_Don_Hang" Member="San_Pham" ThisKey="ID_SP" OtherKey="ID_SP" Type="San_Pham" IsForeignKey="true" />
    </Type>
  </Table>
</Database>