#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cua_Hang_Tra_Sua
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Cua_Hang_Tra_Sua")]
	public partial class Cua_Hang_Tra_SuaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertBai_Viet(Bai_Viet instance);
    partial void UpdateBai_Viet(Bai_Viet instance);
    partial void DeleteBai_Viet(Bai_Viet instance);
    partial void InsertTai_Khoan(Tai_Khoan instance);
    partial void UpdateTai_Khoan(Tai_Khoan instance);
    partial void DeleteTai_Khoan(Tai_Khoan instance);
    partial void InsertChi_Tiet_Don_Hang(Chi_Tiet_Don_Hang instance);
    partial void UpdateChi_Tiet_Don_Hang(Chi_Tiet_Don_Hang instance);
    partial void DeleteChi_Tiet_Don_Hang(Chi_Tiet_Don_Hang instance);
    partial void InsertLich_Su_Don_Hang(Lich_Su_Don_Hang instance);
    partial void UpdateLich_Su_Don_Hang(Lich_Su_Don_Hang instance);
    partial void DeleteLich_Su_Don_Hang(Lich_Su_Don_Hang instance);
    partial void InsertMenus(Menus instance);
    partial void UpdateMenus(Menus instance);
    partial void DeleteMenus(Menus instance);
    partial void InsertSan_Pham(San_Pham instance);
    partial void UpdateSan_Pham(San_Pham instance);
    partial void DeleteSan_Pham(San_Pham instance);
    partial void InsertSP_Don_Hang(SP_Don_Hang instance);
    partial void UpdateSP_Don_Hang(SP_Don_Hang instance);
    partial void DeleteSP_Don_Hang(SP_Don_Hang instance);
    #endregion
		
		public Cua_Hang_Tra_SuaDataContext() : 
				base(global::Cua_Hang_Tra_Sua.Properties.Settings.Default.Cua_Hang_Tra_SuaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Cua_Hang_Tra_SuaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Cua_Hang_Tra_SuaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Cua_Hang_Tra_SuaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Cua_Hang_Tra_SuaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Bai_Viet> Bai_Viets
		{
			get
			{
				return this.GetTable<Bai_Viet>();
			}
		}
		
		public System.Data.Linq.Table<Tai_Khoan> Tai_Khoans
		{
			get
			{
				return this.GetTable<Tai_Khoan>();
			}
		}
		
		public System.Data.Linq.Table<Chi_Tiet_Don_Hang> Chi_Tiet_Don_Hangs
		{
			get
			{
				return this.GetTable<Chi_Tiet_Don_Hang>();
			}
		}
		
		public System.Data.Linq.Table<Lich_Su_Don_Hang> Lich_Su_Don_Hangs
		{
			get
			{
				return this.GetTable<Lich_Su_Don_Hang>();
			}
		}
		
		public System.Data.Linq.Table<Menus> Menus
		{
			get
			{
				return this.GetTable<Menus>();
			}
		}
		
		public System.Data.Linq.Table<San_Pham> San_Phams
		{
			get
			{
				return this.GetTable<San_Pham>();
			}
		}
		
		public System.Data.Linq.Table<SP_Don_Hang> SP_Don_Hangs
		{
			get
			{
				return this.GetTable<SP_Don_Hang>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Bai_Viet")]
	public partial class Bai_Viet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_BV;
		
		private int _ID_MN;
		
		private string _Tieu_de;
		
		private string _Tom_tac;
		
		private string _Noi_dung;
		
		private string _Hinh_anh_page;
		
		private System.Nullable<int> _OrderKey;
		
		private EntityRef<Menus> _Menus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_BVChanging(int value);
    partial void OnID_BVChanged();
    partial void OnID_MNChanging(int value);
    partial void OnID_MNChanged();
    partial void OnTieu_deChanging(string value);
    partial void OnTieu_deChanged();
    partial void OnTom_tacChanging(string value);
    partial void OnTom_tacChanged();
    partial void OnNoi_dungChanging(string value);
    partial void OnNoi_dungChanged();
    partial void OnHinh_anh_pageChanging(string value);
    partial void OnHinh_anh_pageChanged();
    partial void OnOrderKeyChanging(System.Nullable<int> value);
    partial void OnOrderKeyChanged();
    #endregion
		
		public Bai_Viet()
		{
			this._Menus = default(EntityRef<Menus>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_BV", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_BV
		{
			get
			{
				return this._ID_BV;
			}
			set
			{
				if ((this._ID_BV != value))
				{
					this.OnID_BVChanging(value);
					this.SendPropertyChanging();
					this._ID_BV = value;
					this.SendPropertyChanged("ID_BV");
					this.OnID_BVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MN", DbType="Int NOT NULL")]
		public int ID_MN
		{
			get
			{
				return this._ID_MN;
			}
			set
			{
				if ((this._ID_MN != value))
				{
					if (this._Menus.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_MNChanging(value);
					this.SendPropertyChanging();
					this._ID_MN = value;
					this.SendPropertyChanged("ID_MN");
					this.OnID_MNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tieu_de", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Tieu_de
		{
			get
			{
				return this._Tieu_de;
			}
			set
			{
				if ((this._Tieu_de != value))
				{
					this.OnTieu_deChanging(value);
					this.SendPropertyChanging();
					this._Tieu_de = value;
					this.SendPropertyChanged("Tieu_de");
					this.OnTieu_deChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tom_tac", DbType="NVarChar(MAX)")]
		public string Tom_tac
		{
			get
			{
				return this._Tom_tac;
			}
			set
			{
				if ((this._Tom_tac != value))
				{
					this.OnTom_tacChanging(value);
					this.SendPropertyChanging();
					this._Tom_tac = value;
					this.SendPropertyChanged("Tom_tac");
					this.OnTom_tacChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Noi_dung", DbType="NVarChar(MAX) NOT NULL", CanBeNull=false)]
		public string Noi_dung
		{
			get
			{
				return this._Noi_dung;
			}
			set
			{
				if ((this._Noi_dung != value))
				{
					this.OnNoi_dungChanging(value);
					this.SendPropertyChanging();
					this._Noi_dung = value;
					this.SendPropertyChanged("Noi_dung");
					this.OnNoi_dungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh_anh_page", DbType="VarChar(255)")]
		public string Hinh_anh_page
		{
			get
			{
				return this._Hinh_anh_page;
			}
			set
			{
				if ((this._Hinh_anh_page != value))
				{
					this.OnHinh_anh_pageChanging(value);
					this.SendPropertyChanging();
					this._Hinh_anh_page = value;
					this.SendPropertyChanged("Hinh_anh_page");
					this.OnHinh_anh_pageChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderKey", DbType="Int")]
		public System.Nullable<int> OrderKey
		{
			get
			{
				return this._OrderKey;
			}
			set
			{
				if ((this._OrderKey != value))
				{
					this.OnOrderKeyChanging(value);
					this.SendPropertyChanging();
					this._OrderKey = value;
					this.SendPropertyChanged("OrderKey");
					this.OnOrderKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Menus_Bai_Viet", Storage="_Menus", ThisKey="ID_MN", OtherKey="ID_MN", IsForeignKey=true)]
		public Menus Menus
		{
			get
			{
				return this._Menus.Entity;
			}
			set
			{
				Menus previousValue = this._Menus.Entity;
				if (((previousValue != value) 
							|| (this._Menus.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Menus.Entity = null;
						previousValue.Bai_Viets.Remove(this);
					}
					this._Menus.Entity = value;
					if ((value != null))
					{
						value.Bai_Viets.Add(this);
						this._ID_MN = value.ID_MN;
					}
					else
					{
						this._ID_MN = default(int);
					}
					this.SendPropertyChanged("Menus");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Tai_Khoan")]
	public partial class Tai_Khoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Ho_va_ten;
		
		private string _So_dien_thoai;
		
		private string _Dia_chi;
		
		private string _Mat_khau;
		
		private string _Phan_quyen;
		
		private EntitySet<Chi_Tiet_Don_Hang> _Chi_Tiet_Don_Hangs;
		
		private EntitySet<Lich_Su_Don_Hang> _Lich_Su_Don_Hangs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnHo_va_tenChanging(string value);
    partial void OnHo_va_tenChanged();
    partial void OnSo_dien_thoaiChanging(string value);
    partial void OnSo_dien_thoaiChanged();
    partial void OnDia_chiChanging(string value);
    partial void OnDia_chiChanged();
    partial void OnMat_khauChanging(string value);
    partial void OnMat_khauChanged();
    partial void OnPhan_quyenChanging(string value);
    partial void OnPhan_quyenChanged();
    #endregion
		
		public Tai_Khoan()
		{
			this._Chi_Tiet_Don_Hangs = new EntitySet<Chi_Tiet_Don_Hang>(new Action<Chi_Tiet_Don_Hang>(this.attach_Chi_Tiet_Don_Hangs), new Action<Chi_Tiet_Don_Hang>(this.detach_Chi_Tiet_Don_Hangs));
			this._Lich_Su_Don_Hangs = new EntitySet<Lich_Su_Don_Hang>(new Action<Lich_Su_Don_Hang>(this.attach_Lich_Su_Don_Hangs), new Action<Lich_Su_Don_Hang>(this.detach_Lich_Su_Don_Hangs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ho_va_ten", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Ho_va_ten
		{
			get
			{
				return this._Ho_va_ten;
			}
			set
			{
				if ((this._Ho_va_ten != value))
				{
					this.OnHo_va_tenChanging(value);
					this.SendPropertyChanging();
					this._Ho_va_ten = value;
					this.SendPropertyChanged("Ho_va_ten");
					this.OnHo_va_tenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_dien_thoai", DbType="VarChar(15) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string So_dien_thoai
		{
			get
			{
				return this._So_dien_thoai;
			}
			set
			{
				if ((this._So_dien_thoai != value))
				{
					this.OnSo_dien_thoaiChanging(value);
					this.SendPropertyChanging();
					this._So_dien_thoai = value;
					this.SendPropertyChanged("So_dien_thoai");
					this.OnSo_dien_thoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dia_chi", DbType="NVarChar(255)")]
		public string Dia_chi
		{
			get
			{
				return this._Dia_chi;
			}
			set
			{
				if ((this._Dia_chi != value))
				{
					this.OnDia_chiChanging(value);
					this.SendPropertyChanging();
					this._Dia_chi = value;
					this.SendPropertyChanged("Dia_chi");
					this.OnDia_chiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mat_khau", DbType="VarChar(100) NOT NULL", CanBeNull=false)]
		public string Mat_khau
		{
			get
			{
				return this._Mat_khau;
			}
			set
			{
				if ((this._Mat_khau != value))
				{
					this.OnMat_khauChanging(value);
					this.SendPropertyChanging();
					this._Mat_khau = value;
					this.SendPropertyChanged("Mat_khau");
					this.OnMat_khauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phan_quyen", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Phan_quyen
		{
			get
			{
				return this._Phan_quyen;
			}
			set
			{
				if ((this._Phan_quyen != value))
				{
					this.OnPhan_quyenChanging(value);
					this.SendPropertyChanging();
					this._Phan_quyen = value;
					this.SendPropertyChanged("Phan_quyen");
					this.OnPhan_quyenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tai_Khoan_Chi_Tiet_Don_Hang", Storage="_Chi_Tiet_Don_Hangs", ThisKey="So_dien_thoai", OtherKey="So_dien_thoai")]
		public EntitySet<Chi_Tiet_Don_Hang> Chi_Tiet_Don_Hangs
		{
			get
			{
				return this._Chi_Tiet_Don_Hangs;
			}
			set
			{
				this._Chi_Tiet_Don_Hangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tai_Khoan_Lich_Su_Don_Hang", Storage="_Lich_Su_Don_Hangs", ThisKey="So_dien_thoai", OtherKey="So_dien_thoai")]
		public EntitySet<Lich_Su_Don_Hang> Lich_Su_Don_Hangs
		{
			get
			{
				return this._Lich_Su_Don_Hangs;
			}
			set
			{
				this._Lich_Su_Don_Hangs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Chi_Tiet_Don_Hangs(Chi_Tiet_Don_Hang entity)
		{
			this.SendPropertyChanging();
			entity.Tai_Khoan = this;
		}
		
		private void detach_Chi_Tiet_Don_Hangs(Chi_Tiet_Don_Hang entity)
		{
			this.SendPropertyChanging();
			entity.Tai_Khoan = null;
		}
		
		private void attach_Lich_Su_Don_Hangs(Lich_Su_Don_Hang entity)
		{
			this.SendPropertyChanging();
			entity.Tai_Khoan = this;
		}
		
		private void detach_Lich_Su_Don_Hangs(Lich_Su_Don_Hang entity)
		{
			this.SendPropertyChanging();
			entity.Tai_Khoan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Chi_Tiet_Don_Hang")]
	public partial class Chi_Tiet_Don_Hang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_CTDH;
		
		private string _So_dien_thoai;
		
		private string _Hinh_thuc_dat_don;
		
		private string _Trang_thai_don;
		
		private decimal _Tong_tien;
		
		private string _Ghi_chu;
		
		private EntitySet<SP_Don_Hang> _SP_Don_Hangs;
		
		private EntityRef<Tai_Khoan> _Tai_Khoan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_CTDHChanging(int value);
    partial void OnID_CTDHChanged();
    partial void OnSo_dien_thoaiChanging(string value);
    partial void OnSo_dien_thoaiChanged();
    partial void OnHinh_thuc_dat_donChanging(string value);
    partial void OnHinh_thuc_dat_donChanged();
    partial void OnTrang_thai_donChanging(string value);
    partial void OnTrang_thai_donChanged();
    partial void OnTong_tienChanging(decimal value);
    partial void OnTong_tienChanged();
    partial void OnGhi_chuChanging(string value);
    partial void OnGhi_chuChanged();
    #endregion
		
		public Chi_Tiet_Don_Hang()
		{
			this._SP_Don_Hangs = new EntitySet<SP_Don_Hang>(new Action<SP_Don_Hang>(this.attach_SP_Don_Hangs), new Action<SP_Don_Hang>(this.detach_SP_Don_Hangs));
			this._Tai_Khoan = default(EntityRef<Tai_Khoan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CTDH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_CTDH
		{
			get
			{
				return this._ID_CTDH;
			}
			set
			{
				if ((this._ID_CTDH != value))
				{
					this.OnID_CTDHChanging(value);
					this.SendPropertyChanging();
					this._ID_CTDH = value;
					this.SendPropertyChanged("ID_CTDH");
					this.OnID_CTDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_dien_thoai", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string So_dien_thoai
		{
			get
			{
				return this._So_dien_thoai;
			}
			set
			{
				if ((this._So_dien_thoai != value))
				{
					if (this._Tai_Khoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSo_dien_thoaiChanging(value);
					this.SendPropertyChanging();
					this._So_dien_thoai = value;
					this.SendPropertyChanged("So_dien_thoai");
					this.OnSo_dien_thoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh_thuc_dat_don", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Hinh_thuc_dat_don
		{
			get
			{
				return this._Hinh_thuc_dat_don;
			}
			set
			{
				if ((this._Hinh_thuc_dat_don != value))
				{
					this.OnHinh_thuc_dat_donChanging(value);
					this.SendPropertyChanging();
					this._Hinh_thuc_dat_don = value;
					this.SendPropertyChanged("Hinh_thuc_dat_don");
					this.OnHinh_thuc_dat_donChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trang_thai_don", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Trang_thai_don
		{
			get
			{
				return this._Trang_thai_don;
			}
			set
			{
				if ((this._Trang_thai_don != value))
				{
					this.OnTrang_thai_donChanging(value);
					this.SendPropertyChanging();
					this._Trang_thai_don = value;
					this.SendPropertyChanged("Trang_thai_don");
					this.OnTrang_thai_donChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tong_tien", DbType="Decimal(10,2) NOT NULL")]
		public decimal Tong_tien
		{
			get
			{
				return this._Tong_tien;
			}
			set
			{
				if ((this._Tong_tien != value))
				{
					this.OnTong_tienChanging(value);
					this.SendPropertyChanging();
					this._Tong_tien = value;
					this.SendPropertyChanged("Tong_tien");
					this.OnTong_tienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ghi_chu", DbType="NVarChar(255)")]
		public string Ghi_chu
		{
			get
			{
				return this._Ghi_chu;
			}
			set
			{
				if ((this._Ghi_chu != value))
				{
					this.OnGhi_chuChanging(value);
					this.SendPropertyChanging();
					this._Ghi_chu = value;
					this.SendPropertyChanged("Ghi_chu");
					this.OnGhi_chuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Chi_Tiet_Don_Hang_SP_Don_Hang", Storage="_SP_Don_Hangs", ThisKey="ID_CTDH", OtherKey="ID_CTDH")]
		public EntitySet<SP_Don_Hang> SP_Don_Hangs
		{
			get
			{
				return this._SP_Don_Hangs;
			}
			set
			{
				this._SP_Don_Hangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tai_Khoan_Chi_Tiet_Don_Hang", Storage="_Tai_Khoan", ThisKey="So_dien_thoai", OtherKey="So_dien_thoai", IsForeignKey=true)]
		public Tai_Khoan Tai_Khoan
		{
			get
			{
				return this._Tai_Khoan.Entity;
			}
			set
			{
				Tai_Khoan previousValue = this._Tai_Khoan.Entity;
				if (((previousValue != value) 
							|| (this._Tai_Khoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tai_Khoan.Entity = null;
						previousValue.Chi_Tiet_Don_Hangs.Remove(this);
					}
					this._Tai_Khoan.Entity = value;
					if ((value != null))
					{
						value.Chi_Tiet_Don_Hangs.Add(this);
						this._So_dien_thoai = value.So_dien_thoai;
					}
					else
					{
						this._So_dien_thoai = default(string);
					}
					this.SendPropertyChanged("Tai_Khoan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SP_Don_Hangs(SP_Don_Hang entity)
		{
			this.SendPropertyChanging();
			entity.Chi_Tiet_Don_Hang = this;
		}
		
		private void detach_SP_Don_Hangs(SP_Don_Hang entity)
		{
			this.SendPropertyChanging();
			entity.Chi_Tiet_Don_Hang = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Lich_Su_Don_Hang")]
	public partial class Lich_Su_Don_Hang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_LSDH;
		
		private int _ID_DH;
		
		private string _So_dien_thoai;
		
		private System.DateTime _Ngay_gio_ghi_nhan;
		
		private string _Trang_thai;
		
		private string _Ghi_chu;
		
		private EntityRef<Tai_Khoan> _Tai_Khoan;
		
		private EntityRef<SP_Don_Hang> _SP_Don_Hang;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_LSDHChanging(int value);
    partial void OnID_LSDHChanged();
    partial void OnID_DHChanging(int value);
    partial void OnID_DHChanged();
    partial void OnSo_dien_thoaiChanging(string value);
    partial void OnSo_dien_thoaiChanged();
    partial void OnNgay_gio_ghi_nhanChanging(System.DateTime value);
    partial void OnNgay_gio_ghi_nhanChanged();
    partial void OnTrang_thaiChanging(string value);
    partial void OnTrang_thaiChanged();
    partial void OnGhi_chuChanging(string value);
    partial void OnGhi_chuChanged();
    #endregion
		
		public Lich_Su_Don_Hang()
		{
			this._Tai_Khoan = default(EntityRef<Tai_Khoan>);
			this._SP_Don_Hang = default(EntityRef<SP_Don_Hang>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_LSDH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_LSDH
		{
			get
			{
				return this._ID_LSDH;
			}
			set
			{
				if ((this._ID_LSDH != value))
				{
					this.OnID_LSDHChanging(value);
					this.SendPropertyChanging();
					this._ID_LSDH = value;
					this.SendPropertyChanged("ID_LSDH");
					this.OnID_LSDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DH", DbType="Int NOT NULL")]
		public int ID_DH
		{
			get
			{
				return this._ID_DH;
			}
			set
			{
				if ((this._ID_DH != value))
				{
					if (this._SP_Don_Hang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_DHChanging(value);
					this.SendPropertyChanging();
					this._ID_DH = value;
					this.SendPropertyChanged("ID_DH");
					this.OnID_DHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_dien_thoai", DbType="VarChar(15) NOT NULL", CanBeNull=false)]
		public string So_dien_thoai
		{
			get
			{
				return this._So_dien_thoai;
			}
			set
			{
				if ((this._So_dien_thoai != value))
				{
					if (this._Tai_Khoan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnSo_dien_thoaiChanging(value);
					this.SendPropertyChanging();
					this._So_dien_thoai = value;
					this.SendPropertyChanged("So_dien_thoai");
					this.OnSo_dien_thoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngay_gio_ghi_nhan", DbType="DateTime NOT NULL")]
		public System.DateTime Ngay_gio_ghi_nhan
		{
			get
			{
				return this._Ngay_gio_ghi_nhan;
			}
			set
			{
				if ((this._Ngay_gio_ghi_nhan != value))
				{
					this.OnNgay_gio_ghi_nhanChanging(value);
					this.SendPropertyChanging();
					this._Ngay_gio_ghi_nhan = value;
					this.SendPropertyChanged("Ngay_gio_ghi_nhan");
					this.OnNgay_gio_ghi_nhanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trang_thai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Trang_thai
		{
			get
			{
				return this._Trang_thai;
			}
			set
			{
				if ((this._Trang_thai != value))
				{
					this.OnTrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._Trang_thai = value;
					this.SendPropertyChanged("Trang_thai");
					this.OnTrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ghi_chu", DbType="NVarChar(MAX)")]
		public string Ghi_chu
		{
			get
			{
				return this._Ghi_chu;
			}
			set
			{
				if ((this._Ghi_chu != value))
				{
					this.OnGhi_chuChanging(value);
					this.SendPropertyChanging();
					this._Ghi_chu = value;
					this.SendPropertyChanged("Ghi_chu");
					this.OnGhi_chuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Tai_Khoan_Lich_Su_Don_Hang", Storage="_Tai_Khoan", ThisKey="So_dien_thoai", OtherKey="So_dien_thoai", IsForeignKey=true)]
		public Tai_Khoan Tai_Khoan
		{
			get
			{
				return this._Tai_Khoan.Entity;
			}
			set
			{
				Tai_Khoan previousValue = this._Tai_Khoan.Entity;
				if (((previousValue != value) 
							|| (this._Tai_Khoan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Tai_Khoan.Entity = null;
						previousValue.Lich_Su_Don_Hangs.Remove(this);
					}
					this._Tai_Khoan.Entity = value;
					if ((value != null))
					{
						value.Lich_Su_Don_Hangs.Add(this);
						this._So_dien_thoai = value.So_dien_thoai;
					}
					else
					{
						this._So_dien_thoai = default(string);
					}
					this.SendPropertyChanged("Tai_Khoan");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SP_Don_Hang_Lich_Su_Don_Hang", Storage="_SP_Don_Hang", ThisKey="ID_DH", OtherKey="ID_DH", IsForeignKey=true)]
		public SP_Don_Hang SP_Don_Hang
		{
			get
			{
				return this._SP_Don_Hang.Entity;
			}
			set
			{
				SP_Don_Hang previousValue = this._SP_Don_Hang.Entity;
				if (((previousValue != value) 
							|| (this._SP_Don_Hang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._SP_Don_Hang.Entity = null;
						previousValue.Lich_Su_Don_Hangs.Remove(this);
					}
					this._SP_Don_Hang.Entity = value;
					if ((value != null))
					{
						value.Lich_Su_Don_Hangs.Add(this);
						this._ID_DH = value.ID_DH;
					}
					else
					{
						this._ID_DH = default(int);
					}
					this.SendPropertyChanged("SP_Don_Hang");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Menus")]
	public partial class Menus : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_MN;
		
		private System.Nullable<int> _Parent;
		
		private string _Label;
		
		private string _UrlLink;
		
		private System.Nullable<int> _OrderKey;
		
		private EntitySet<Bai_Viet> _Bai_Viets;
		
		private EntitySet<San_Pham> _San_Phams;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_MNChanging(int value);
    partial void OnID_MNChanged();
    partial void OnParentChanging(System.Nullable<int> value);
    partial void OnParentChanged();
    partial void OnLabelChanging(string value);
    partial void OnLabelChanged();
    partial void OnUrlLinkChanging(string value);
    partial void OnUrlLinkChanged();
    partial void OnOrderKeyChanging(System.Nullable<int> value);
    partial void OnOrderKeyChanged();
    #endregion
		
		public Menus()
		{
			this._Bai_Viets = new EntitySet<Bai_Viet>(new Action<Bai_Viet>(this.attach_Bai_Viets), new Action<Bai_Viet>(this.detach_Bai_Viets));
			this._San_Phams = new EntitySet<San_Pham>(new Action<San_Pham>(this.attach_San_Phams), new Action<San_Pham>(this.detach_San_Phams));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_MN
		{
			get
			{
				return this._ID_MN;
			}
			set
			{
				if ((this._ID_MN != value))
				{
					this.OnID_MNChanging(value);
					this.SendPropertyChanging();
					this._ID_MN = value;
					this.SendPropertyChanged("ID_MN");
					this.OnID_MNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Parent", DbType="Int")]
		public System.Nullable<int> Parent
		{
			get
			{
				return this._Parent;
			}
			set
			{
				if ((this._Parent != value))
				{
					this.OnParentChanging(value);
					this.SendPropertyChanging();
					this._Parent = value;
					this.SendPropertyChanged("Parent");
					this.OnParentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Label", DbType="NVarChar(100) NOT NULL", CanBeNull=false)]
		public string Label
		{
			get
			{
				return this._Label;
			}
			set
			{
				if ((this._Label != value))
				{
					this.OnLabelChanging(value);
					this.SendPropertyChanging();
					this._Label = value;
					this.SendPropertyChanged("Label");
					this.OnLabelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UrlLink", DbType="VarChar(255)")]
		public string UrlLink
		{
			get
			{
				return this._UrlLink;
			}
			set
			{
				if ((this._UrlLink != value))
				{
					this.OnUrlLinkChanging(value);
					this.SendPropertyChanging();
					this._UrlLink = value;
					this.SendPropertyChanged("UrlLink");
					this.OnUrlLinkChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_OrderKey", DbType="Int")]
		public System.Nullable<int> OrderKey
		{
			get
			{
				return this._OrderKey;
			}
			set
			{
				if ((this._OrderKey != value))
				{
					this.OnOrderKeyChanging(value);
					this.SendPropertyChanging();
					this._OrderKey = value;
					this.SendPropertyChanged("OrderKey");
					this.OnOrderKeyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Menus_Bai_Viet", Storage="_Bai_Viets", ThisKey="ID_MN", OtherKey="ID_MN")]
		public EntitySet<Bai_Viet> Bai_Viets
		{
			get
			{
				return this._Bai_Viets;
			}
			set
			{
				this._Bai_Viets.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Menus_San_Pham", Storage="_San_Phams", ThisKey="ID_MN", OtherKey="ID_MN")]
		public EntitySet<San_Pham> San_Phams
		{
			get
			{
				return this._San_Phams;
			}
			set
			{
				this._San_Phams.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Bai_Viets(Bai_Viet entity)
		{
			this.SendPropertyChanging();
			entity.Menus = this;
		}
		
		private void detach_Bai_Viets(Bai_Viet entity)
		{
			this.SendPropertyChanging();
			entity.Menus = null;
		}
		
		private void attach_San_Phams(San_Pham entity)
		{
			this.SendPropertyChanging();
			entity.Menus = this;
		}
		
		private void detach_San_Phams(San_Pham entity)
		{
			this.SendPropertyChanging();
			entity.Menus = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.San_Pham")]
	public partial class San_Pham : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_SP;
		
		private int _ID_MN;
		
		private string _Ten_san_pham;
		
		private decimal _Gia_co_ban;
		
		private string _Mo_ta_san_pham;
		
		private string _Hinh_anh;
		
		private string _Trang_thai;
		
		private EntitySet<SP_Don_Hang> _SP_Don_Hangs;
		
		private EntityRef<Menus> _Menus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_SPChanging(int value);
    partial void OnID_SPChanged();
    partial void OnID_MNChanging(int value);
    partial void OnID_MNChanged();
    partial void OnTen_san_phamChanging(string value);
    partial void OnTen_san_phamChanged();
    partial void OnGia_co_banChanging(decimal value);
    partial void OnGia_co_banChanged();
    partial void OnMo_ta_san_phamChanging(string value);
    partial void OnMo_ta_san_phamChanged();
    partial void OnHinh_anhChanging(string value);
    partial void OnHinh_anhChanged();
    partial void OnTrang_thaiChanging(string value);
    partial void OnTrang_thaiChanged();
    #endregion
		
		public San_Pham()
		{
			this._SP_Don_Hangs = new EntitySet<SP_Don_Hang>(new Action<SP_Don_Hang>(this.attach_SP_Don_Hangs), new Action<SP_Don_Hang>(this.detach_SP_Don_Hangs));
			this._Menus = default(EntityRef<Menus>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SP", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_SP
		{
			get
			{
				return this._ID_SP;
			}
			set
			{
				if ((this._ID_SP != value))
				{
					this.OnID_SPChanging(value);
					this.SendPropertyChanging();
					this._ID_SP = value;
					this.SendPropertyChanged("ID_SP");
					this.OnID_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_MN", DbType="Int NOT NULL")]
		public int ID_MN
		{
			get
			{
				return this._ID_MN;
			}
			set
			{
				if ((this._ID_MN != value))
				{
					if (this._Menus.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_MNChanging(value);
					this.SendPropertyChanging();
					this._ID_MN = value;
					this.SendPropertyChanged("ID_MN");
					this.OnID_MNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ten_san_pham", DbType="NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Ten_san_pham
		{
			get
			{
				return this._Ten_san_pham;
			}
			set
			{
				if ((this._Ten_san_pham != value))
				{
					this.OnTen_san_phamChanging(value);
					this.SendPropertyChanging();
					this._Ten_san_pham = value;
					this.SendPropertyChanged("Ten_san_pham");
					this.OnTen_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia_co_ban", DbType="Decimal(10,2) NOT NULL")]
		public decimal Gia_co_ban
		{
			get
			{
				return this._Gia_co_ban;
			}
			set
			{
				if ((this._Gia_co_ban != value))
				{
					this.OnGia_co_banChanging(value);
					this.SendPropertyChanging();
					this._Gia_co_ban = value;
					this.SendPropertyChanged("Gia_co_ban");
					this.OnGia_co_banChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Mo_ta_san_pham", DbType="NVarChar(MAX)")]
		public string Mo_ta_san_pham
		{
			get
			{
				return this._Mo_ta_san_pham;
			}
			set
			{
				if ((this._Mo_ta_san_pham != value))
				{
					this.OnMo_ta_san_phamChanging(value);
					this.SendPropertyChanging();
					this._Mo_ta_san_pham = value;
					this.SendPropertyChanged("Mo_ta_san_pham");
					this.OnMo_ta_san_phamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hinh_anh", DbType="VarChar(255)")]
		public string Hinh_anh
		{
			get
			{
				return this._Hinh_anh;
			}
			set
			{
				if ((this._Hinh_anh != value))
				{
					this.OnHinh_anhChanging(value);
					this.SendPropertyChanging();
					this._Hinh_anh = value;
					this.SendPropertyChanged("Hinh_anh");
					this.OnHinh_anhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trang_thai", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Trang_thai
		{
			get
			{
				return this._Trang_thai;
			}
			set
			{
				if ((this._Trang_thai != value))
				{
					this.OnTrang_thaiChanging(value);
					this.SendPropertyChanging();
					this._Trang_thai = value;
					this.SendPropertyChanged("Trang_thai");
					this.OnTrang_thaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="San_Pham_SP_Don_Hang", Storage="_SP_Don_Hangs", ThisKey="ID_SP", OtherKey="ID_SP")]
		public EntitySet<SP_Don_Hang> SP_Don_Hangs
		{
			get
			{
				return this._SP_Don_Hangs;
			}
			set
			{
				this._SP_Don_Hangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Menus_San_Pham", Storage="_Menus", ThisKey="ID_MN", OtherKey="ID_MN", IsForeignKey=true)]
		public Menus Menus
		{
			get
			{
				return this._Menus.Entity;
			}
			set
			{
				Menus previousValue = this._Menus.Entity;
				if (((previousValue != value) 
							|| (this._Menus.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Menus.Entity = null;
						previousValue.San_Phams.Remove(this);
					}
					this._Menus.Entity = value;
					if ((value != null))
					{
						value.San_Phams.Add(this);
						this._ID_MN = value.ID_MN;
					}
					else
					{
						this._ID_MN = default(int);
					}
					this.SendPropertyChanged("Menus");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SP_Don_Hangs(SP_Don_Hang entity)
		{
			this.SendPropertyChanging();
			entity.San_Pham = this;
		}
		
		private void detach_SP_Don_Hangs(SP_Don_Hang entity)
		{
			this.SendPropertyChanging();
			entity.San_Pham = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SP_Don_Hang")]
	public partial class SP_Don_Hang : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID_DH;
		
		private int _ID_CTDH;
		
		private int _ID_SP;
		
		private int _So_luong;
		
		private decimal _Gia_Ban;
		
		private string _Ghi_chu_item;
		
		private EntitySet<Lich_Su_Don_Hang> _Lich_Su_Don_Hangs;
		
		private EntityRef<Chi_Tiet_Don_Hang> _Chi_Tiet_Don_Hang;
		
		private EntityRef<San_Pham> _San_Pham;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnID_DHChanging(int value);
    partial void OnID_DHChanged();
    partial void OnID_CTDHChanging(int value);
    partial void OnID_CTDHChanged();
    partial void OnID_SPChanging(int value);
    partial void OnID_SPChanged();
    partial void OnSo_luongChanging(int value);
    partial void OnSo_luongChanged();
    partial void OnGia_BanChanging(decimal value);
    partial void OnGia_BanChanged();
    partial void OnGhi_chu_itemChanging(string value);
    partial void OnGhi_chu_itemChanged();
    #endregion
		
		public SP_Don_Hang()
		{
			this._Lich_Su_Don_Hangs = new EntitySet<Lich_Su_Don_Hang>(new Action<Lich_Su_Don_Hang>(this.attach_Lich_Su_Don_Hangs), new Action<Lich_Su_Don_Hang>(this.detach_Lich_Su_Don_Hangs));
			this._Chi_Tiet_Don_Hang = default(EntityRef<Chi_Tiet_Don_Hang>);
			this._San_Pham = default(EntityRef<San_Pham>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_DH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID_DH
		{
			get
			{
				return this._ID_DH;
			}
			set
			{
				if ((this._ID_DH != value))
				{
					this.OnID_DHChanging(value);
					this.SendPropertyChanging();
					this._ID_DH = value;
					this.SendPropertyChanged("ID_DH");
					this.OnID_DHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_CTDH", DbType="Int NOT NULL")]
		public int ID_CTDH
		{
			get
			{
				return this._ID_CTDH;
			}
			set
			{
				if ((this._ID_CTDH != value))
				{
					if (this._Chi_Tiet_Don_Hang.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_CTDHChanging(value);
					this.SendPropertyChanging();
					this._ID_CTDH = value;
					this.SendPropertyChanged("ID_CTDH");
					this.OnID_CTDHChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID_SP", DbType="Int NOT NULL")]
		public int ID_SP
		{
			get
			{
				return this._ID_SP;
			}
			set
			{
				if ((this._ID_SP != value))
				{
					if (this._San_Pham.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnID_SPChanging(value);
					this.SendPropertyChanging();
					this._ID_SP = value;
					this.SendPropertyChanged("ID_SP");
					this.OnID_SPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_So_luong", DbType="Int NOT NULL")]
		public int So_luong
		{
			get
			{
				return this._So_luong;
			}
			set
			{
				if ((this._So_luong != value))
				{
					this.OnSo_luongChanging(value);
					this.SendPropertyChanging();
					this._So_luong = value;
					this.SendPropertyChanged("So_luong");
					this.OnSo_luongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia_Ban", DbType="Decimal(10,2) NOT NULL")]
		public decimal Gia_Ban
		{
			get
			{
				return this._Gia_Ban;
			}
			set
			{
				if ((this._Gia_Ban != value))
				{
					this.OnGia_BanChanging(value);
					this.SendPropertyChanging();
					this._Gia_Ban = value;
					this.SendPropertyChanged("Gia_Ban");
					this.OnGia_BanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ghi_chu_item", DbType="NVarChar(MAX)")]
		public string Ghi_chu_item
		{
			get
			{
				return this._Ghi_chu_item;
			}
			set
			{
				if ((this._Ghi_chu_item != value))
				{
					this.OnGhi_chu_itemChanging(value);
					this.SendPropertyChanging();
					this._Ghi_chu_item = value;
					this.SendPropertyChanged("Ghi_chu_item");
					this.OnGhi_chu_itemChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="SP_Don_Hang_Lich_Su_Don_Hang", Storage="_Lich_Su_Don_Hangs", ThisKey="ID_DH", OtherKey="ID_DH")]
		public EntitySet<Lich_Su_Don_Hang> Lich_Su_Don_Hangs
		{
			get
			{
				return this._Lich_Su_Don_Hangs;
			}
			set
			{
				this._Lich_Su_Don_Hangs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Chi_Tiet_Don_Hang_SP_Don_Hang", Storage="_Chi_Tiet_Don_Hang", ThisKey="ID_CTDH", OtherKey="ID_CTDH", IsForeignKey=true)]
		public Chi_Tiet_Don_Hang Chi_Tiet_Don_Hang
		{
			get
			{
				return this._Chi_Tiet_Don_Hang.Entity;
			}
			set
			{
				Chi_Tiet_Don_Hang previousValue = this._Chi_Tiet_Don_Hang.Entity;
				if (((previousValue != value) 
							|| (this._Chi_Tiet_Don_Hang.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Chi_Tiet_Don_Hang.Entity = null;
						previousValue.SP_Don_Hangs.Remove(this);
					}
					this._Chi_Tiet_Don_Hang.Entity = value;
					if ((value != null))
					{
						value.SP_Don_Hangs.Add(this);
						this._ID_CTDH = value.ID_CTDH;
					}
					else
					{
						this._ID_CTDH = default(int);
					}
					this.SendPropertyChanged("Chi_Tiet_Don_Hang");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="San_Pham_SP_Don_Hang", Storage="_San_Pham", ThisKey="ID_SP", OtherKey="ID_SP", IsForeignKey=true)]
		public San_Pham San_Pham
		{
			get
			{
				return this._San_Pham.Entity;
			}
			set
			{
				San_Pham previousValue = this._San_Pham.Entity;
				if (((previousValue != value) 
							|| (this._San_Pham.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._San_Pham.Entity = null;
						previousValue.SP_Don_Hangs.Remove(this);
					}
					this._San_Pham.Entity = value;
					if ((value != null))
					{
						value.SP_Don_Hangs.Add(this);
						this._ID_SP = value.ID_SP;
					}
					else
					{
						this._ID_SP = default(int);
					}
					this.SendPropertyChanged("San_Pham");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Lich_Su_Don_Hangs(Lich_Su_Don_Hang entity)
		{
			this.SendPropertyChanging();
			entity.SP_Don_Hang = this;
		}
		
		private void detach_Lich_Su_Don_Hangs(Lich_Su_Don_Hang entity)
		{
			this.SendPropertyChanging();
			entity.SP_Don_Hang = null;
		}
	}
}
#pragma warning restore 1591
