<?xml version="1.0" encoding="utf-8"?><Database Name="Cua_Hang_Tra_Sua" Class="Cua_Hang_Tra_SuaDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-PCHKGH1\SQLEXPRESS;Initial Catalog=Cua_Hang_Tra_Sua;Integrated Security=True;Encrypt=False;Trust Server Certificate=True" SettingsObjectName="Cua_Hang_Tra_Sua.Properties.Settings" SettingsPropertyName="Cua_Hang_Tra_SuaConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Bai_Viet" Member="Bai_Viets">
    <Type Name="Bai_Viet">
      <Column Name="ID_BV" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_DM" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Tieu_de" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Tom_tac" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Noi_dung" Type="System.String" DbType="NVarChar(MAX) NOT NULL" CanBeNull="false" />
      <Column Name="Hinh_anh_page" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="OrderKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Danh_Muc_Bai_Viet" Member="Danh_Muc" ThisKey="ID_DM" OtherKey="ID_DM" Type="Danh_Muc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Tai_Khoan" Member="Tai_Khoans">
    <Type Name="Tai_Khoan">
      <Column Name="So_dien_thoai" Type="System.String" DbType="VarChar(15) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Ho_va_ten" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Dia_chi" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Mat_khau" Type="System.String" DbType="VarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="Phan_quyen" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ngay_tao" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Tai_Khoan_Gio_Hang" Member="Gio_Hangs" ThisKey="So_dien_thoai" OtherKey="So_dien_thoai" Type="Gio_Hang" />
      <Association Name="Tai_Khoan_Don_Hang" Member="Don_Hangs" ThisKey="So_dien_thoai" OtherKey="So_dien_thoai" Type="Don_Hang" />
    </Type>
  </Table>
  <Table Name="dbo.Chi_Tiet_Don_Hang" Member="Chi_Tiet_Don_Hangs">
    <Type Name="Chi_Tiet_Don_Hang">
      <Column Name="ID_DH" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_SP" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="So_luong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Gia_Ban" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Ghi_chu_item" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="San_Pham_Chi_Tiet_Don_Hang" Member="San_Pham" ThisKey="ID_SP" OtherKey="ID_SP" Type="San_Pham" IsForeignKey="true" />
      <Association Name="Don_Hang_Chi_Tiet_Don_Hang" Member="Don_Hang" ThisKey="ID_DH" OtherKey="ID_DH" Type="Don_Hang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Danh_Muc" Member="Danh_Mucs">
    <Type Name="Danh_Muc">
      <Column Name="ID_DM" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Parent" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Label" Type="System.String" DbType="NVarChar(100) NOT NULL" CanBeNull="false" />
      <Column Name="UrlLink" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="OrderKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Danh_Muc_Bai_Viet" Member="Bai_Viets" ThisKey="ID_DM" OtherKey="ID_DM" Type="Bai_Viet" />
      <Association Name="Danh_Muc_Danh_Muc" Member="Danh_Mucs" ThisKey="ID_DM" OtherKey="Parent" Type="Danh_Muc" />
      <Association Name="Danh_Muc_San_Pham" Member="San_Phams" ThisKey="ID_DM" OtherKey="ID_DM" Type="San_Pham" />
      <Association Name="Danh_Muc_Danh_Muc" Member="Danh_Muc1" ThisKey="Parent" OtherKey="ID_DM" Type="Danh_Muc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Gio_Hang" Member="Gio_Hangs">
    <Type Name="Gio_Hang">
      <Column Name="ID_GH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="So_dien_thoai" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="ID_SP" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="So_luong" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Gia_luc_them" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Ghi_chu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Ngay_them" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="Tai_Khoan_Gio_Hang" Member="Tai_Khoan" ThisKey="So_dien_thoai" OtherKey="So_dien_thoai" Type="Tai_Khoan" IsForeignKey="true" />
      <Association Name="San_Pham_Gio_Hang" Member="San_Pham" ThisKey="ID_SP" OtherKey="ID_SP" Type="San_Pham" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Hinh_Anh_Quan" Member="Hinh_Anh_Quans">
    <Type Name="Hinh_Anh_Quan">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ImageUrl" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="AltText" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="OrderKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Hinh_Anh_Slider" Member="Hinh_Anh_Sliders">
    <Type Name="Hinh_Anh_Slider">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ImageUrl" Type="System.String" DbType="VarChar(255) NOT NULL" CanBeNull="false" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="OrderKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="dbo.Lich_Su_Don_Hang" Member="Lich_Su_Don_Hangs">
    <Type Name="Lich_Su_Don_Hang">
      <Column Name="ID_LSDH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_DH" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ngay_gio_ghi_nhan" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Trang_thai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Ghi_chu" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="Don_Hang_Lich_Su_Don_Hang" Member="Don_Hang" ThisKey="ID_DH" OtherKey="ID_DH" Type="Don_Hang" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.San_Pham" Member="San_Phams">
    <Type Name="San_Pham">
      <Column Name="ID_SP" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ID_DM" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Ten_san_pham" Type="System.String" DbType="NVarChar(200) NOT NULL" CanBeNull="false" />
      <Column Name="Gia_co_ban" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Mo_ta_san_pham" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="Hinh_anh" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="Trang_thai" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="OrderKey" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsHot" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="San_Pham_Chi_Tiet_Don_Hang" Member="Chi_Tiet_Don_Hangs" ThisKey="ID_SP" OtherKey="ID_SP" Type="Chi_Tiet_Don_Hang" />
      <Association Name="San_Pham_Gio_Hang" Member="Gio_Hangs" ThisKey="ID_SP" OtherKey="ID_SP" Type="Gio_Hang" />
      <Association Name="Danh_Muc_San_Pham" Member="Danh_Muc" ThisKey="ID_DM" OtherKey="ID_DM" Type="Danh_Muc" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Don_Hang" Member="Don_Hangs">
    <Type Name="Don_Hang">
      <Column Name="ID_DH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="So_dien_thoai" Type="System.String" DbType="VarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Ngay_tao" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="Hinh_thuc_dat_don" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Trang_thai_don" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Tong_tien" Type="System.Decimal" DbType="Decimal(10,2) NOT NULL" CanBeNull="false" />
      <Column Name="Ghi_chu" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Dia_chi_giao_hang" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Association Name="Don_Hang_Chi_Tiet_Don_Hang" Member="Chi_Tiet_Don_Hangs" ThisKey="ID_DH" OtherKey="ID_DH" Type="Chi_Tiet_Don_Hang" />
      <Association Name="Don_Hang_Lich_Su_Don_Hang" Member="Lich_Su_Don_Hangs" ThisKey="ID_DH" OtherKey="ID_DH" Type="Lich_Su_Don_Hang" />
      <Association Name="Tai_Khoan_Don_Hang" Member="Tai_Khoan" ThisKey="So_dien_thoai" OtherKey="So_dien_thoai" Type="Tai_Khoan" IsForeignKey="true" />
    </Type>
  </Table>
</Database>